version: '3'

services:

  nginx:
    image: jonasal/nginx-certbot:6.2.0
    container_name: nginx
    # ports:
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    #   - "8228:8228/tcp"
    network_mode: "host" # IPv6 please
    volumes:
      - ./nginx/00-nginx-http.conf:/etc/nginx/conf.d/00-nginx-http.conf:ro
      - ./nginx/01-default-server.conf:/etc/nginx/conf.d/01-default-server.conf:ro
      - ./nginx/dex.conf:/etc/nginx/templates/dex.conf.template:ro
      - ./nginx/headscale.conf:/etc/nginx/templates/headscale.conf.template:ro
      - ./nginx/ffdhe2048.pem:/etc/nginx/ffdhe2048.pem:ro
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    env_file: ./secrets/nginx.env

  dex:
    image: ghcr.io/dexidp/dex:v2.45.1
    container_name: dex
    # ports:
    #   - "5558:5558/tcp"
    network_mode: "host"
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
      - dex:/var/dex # for /var/dex/dex.db sqlite3 database
    restart: unless-stopped
    env_file: ./secrets/dex.env

volumes:
  letsencrypt:
  dex:
