# Template for the virtual host
server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen      443 ssl;
    listen [::]:443 ssl;
    http2 on;

    # Domain name this server responds to
    server_name ${DEX_FQDN};

    # Logging in the vhost format
    access_log /var/log/nginx/access.log vhost;

    # Load certificates
    ssl_certificate     /etc/letsencrypt/live/${DEX_FQDN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DEX_FQDN}/privkey.pem;

    # Proxy everything over http to dex
    location / {
        proxy_pass http://127.0.0.1:5556;
    }
}
